# Generated by Django 4.1.5 on 2023-01-15 13:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=40)),
                ('prenom', models.CharField(max_length=50)),
                ('adresse', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=20)),
                ('ville', models.CharField(max_length=20)),
                ('pays', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_location', models.DateTimeField()),
                ('date_retour', models.DateTimeField()),
                ('cout', models.IntegerField()),
                ('client_id', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='rent.client')),
            ],
        ),
        migrations.CreateModel(
            name='Location_tarif',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tarif_jour', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Taille_vehicule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Type_vehicule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_creation', models.DateTimeField()),
                ('cout', models.IntegerField()),
                ('taille_id', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='rent.taille_vehicule')),
                ('type_vehicule_id', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='rent.type_vehicule')),
            ],
        ),
        migrations.RemoveField(
            model_name='rental',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='rental',
            name='vehicle',
        ),
        migrations.RemoveField(
            model_name='rentalrate',
            name='vehicle_size',
        ),
        migrations.RemoveField(
            model_name='rentalrate',
            name='vehicle_type',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='size',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='vehicle_type',
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
        migrations.DeleteModel(
            name='Rental',
        ),
        migrations.DeleteModel(
            name='RentalRate',
        ),
        migrations.DeleteModel(
            name='Vehicle',
        ),
        migrations.DeleteModel(
            name='VehicleSize',
        ),
        migrations.DeleteModel(
            name='VehicleType',
        ),
        migrations.AddField(
            model_name='location_tarif',
            name='taille_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='rent.taille_vehicule'),
        ),
        migrations.AddField(
            model_name='location_tarif',
            name='type_vehicule_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='rent.type_vehicule'),
        ),
        migrations.AddField(
            model_name='location',
            name='vehicule_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='rent.vehicule'),
        ),
    ]
