# Generated by Django 4.1.5 on 2023-01-03 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gifs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='gifs',
        ),
        migrations.AddField(
            model_name='gif',
            name='categories',
            field=models.ManyToManyField(to='gifs.category'),
        ),
    ]
