# Generated by Django 4.1.5 on 2023-01-03 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gifs', '0002_remove_category_gifs_gif_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gif',
            name='categories',
            field=models.ManyToManyField(related_name='gifs', to='gifs.category'),
        ),
    ]
