# Generated by Django 4.1.5 on 2023-01-03 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gifs', '0003_alter_gif_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='gif',
            name='categories',
            field=models.ManyToManyField(to='gifs.category'),
        ),
        migrations.AlterField(
            model_name='gif',
            name='title',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='gif',
            name='uploader_name',
            field=models.CharField(max_length=50),
        ),
    ]
