# Generated by Django 4.1.5 on 2023-01-03 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gifs', '0004_alter_category_name_alter_gif_categories_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='gifs',
            field=models.ManyToManyField(related_name='gifts_categories', to='gifs.gif'),
        ),
    ]
