# Generated by Django 4.1.5 on 2023-01-03 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gifs', '0005_category_gifs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gif',
            name='categories',
        ),
        migrations.AlterField(
            model_name='category',
            name='gifs',
            field=models.ManyToManyField(related_name='categories', to='gifs.gif'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='gif',
            name='title',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='gif',
            name='uploader_name',
            field=models.CharField(max_length=255),
        ),
    ]
