# Generated by Django 4.1.5 on 2023-01-10 12:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=20)),
                ('image', models.ImageField(blank=True, upload_to='images')),
            ],
        ),
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=20)),
                ('detail', models.TextField(max_length=50)),
                ('has_been_done', models.BooleanField(default=False)),
                ('date_creation', models.DateTimeField()),
                ('date_completion', models.DateTimeField()),
                ('date_echeance', models.DateTimeField()),
                ('categorie_id', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='todo.categorie')),
            ],
        ),
    ]
