# Generated by Django 4.1.4 on 2022-12-24 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='nom',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
