# Generated by Django 4.1.5 on 2023-01-23 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_rename_is_publisheb_listing_is_published_and_more'),
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Realtor',
        ),
    ]
