# Generated by Django 4.1.4 on 2022-12-30 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50, null=True)),
                ('email', models.CharField(max_length=50, unique=True)),
                ('phone_number', models.IntegerField(max_length=8)),
                ('adresse', models.TextField(max_length=100, null=True)),
            ],
        ),
    ]
